id: http://farsightsecurity.com/dnstable-manager-config-schema#
$schema: http://json-schema.org/draft-04/schema#
title: dnstable manager
description: configuration for dnstable manager application
type: object
properties:
        manager:
                type: object
                properties:
                        daemon:
                                type: boolean
                        log_stream:
                                type: string
                                enum:
                                        - stderr
                                        - stdout
                        log_file:
                                type: string
                        syslog:
                                type: boolean
                        syslog_facility:
                                type: string
                                enum:
                                        - ALERT
                                        - AUTH
                                        - CONS
                                        - CRIT
                                        - CRON
                                        - DAEMON
                                        - DEBUG
                                        - EMERG
                                        - ERR
                                        - INFO
                                        - KERN
                                        - LOCAL0
                                        - LOCAL1
                                        - LOCAL2
                                        - LOCAL3
                                        - LOCAL4
                                        - LOCAL5
                                        - LOCAL6
                                        - LOCAL7
                                        - LPR
                                        - MAIL
                                        - NDELAY
                                        - NEWS
                                        - NOTICE
                                        - NOWAIT
                                        - PERROR
                                        - PID
                                        - SYSLOG
                                        - USER
                                        - UUCP
                                        - WARNING
                        log_level:
                                type: string
                                enum:
                                        - CRITICAL
                                        - ERROR
                                        - WARNING
                                        - INFO
                                        - DEBUG
                required:
                        - daemon
                        - log_level
        downloader:
                type: object
                properties:
                        max_downloads:
                                type: integer
                                minimum: 1
                        retry_timeout:
                                type: number
                                minimum: 0
                                exclusiveMinimum: true
                        tempdir:
                                type: string
                        rsync_rsh:
                                type: string
                        ssl_ca_file:
                                type: string
                        ssl_keyfile:
                                type: string
                        ssl_certfile:
                                type: string
                        ssl_ciphers:
                                type: string
                required:
                        - max_downloads
                        - retry_timeout
                        - tempdir
                        - rsync_rsh
                        - ssl_ca_file
                        - ssl_ciphers
        filesets:
                type: object
                minProperties: 1
                patternProperties:
                        "^[a-z]+$":
                                type: object
                                properties:
                                        uri:
                                                type: string
                                                format: uri
                                        realm:
                                                type: string
                                        username:
                                                type: string
                                        password:
                                                type: string
                                        destination:
                                                type: string
                                        base:
                                                type: string
                                                pattern: '^[a-z]+(?:--[a-z]+)?$'
                                        extension:
                                                type: string
                                                pattern: '^[a-z]+$'
                                        frequency:
                                                type: number
                                                minimum: 0
                                                exclusiveMinimum: true
                                required:
                                        - uri
                                        - destination
                                        - base
                                        - extension
                                        - frequency
required: 
        - manager
        - downloader
        - filesets
