manager:
        log_file: 
        log_level: ERROR
        syslog: false
        syslog_facility: USER
        daemon: false
downloader:
        max_downloads: 4
        retry_timeout: 60
        tempdir: /tmp
        rsync_rsh: ssh
        ssl_ca_file: /etc/ssl/certs/ca-certificates.crt
        ssl_ciphers: 'EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:!EECDH+aRSA+RC4:EECDH:EDH+aRSA:!RC4:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:@STRENGTH'
filesets:
