manager:
        log_file: 
        log_level: ERROR
        syslog: false
        syslog_facility: USER
        daemon: false
downloader:
        max_downloads: 4
        retry_timeout: 60
        tempdir: /tmp
        rsync_rsh: ssh
filesets:
